title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          text: 
            type: textarea
            required: true
          year:
            type: number
    
  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        image:
          ratio: 16/9
          cover: true