title: Site

tabs:
  pages:
    label: Pages
    sections:
      drafts:
        label: Brouillons
        type: pages
        status: draft
        image: false

      published:
        label: Pages publiées
        type: pages
        status: listed
        image: false

      unpublished:
        label: Pages non listées
        type: pages
        status: unlisted
        image: false
